/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.json  instead.
 *  That file has no code syntax — just fill in your details.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from "@/lib/themes";
import rawConfig from "../portfolio.config.json";

export interface SectionVisibility {
  about:          boolean;
  skills:         boolean;
  experience:     boolean;
  projects:       boolean;
  education:      boolean;
  certifications: boolean;
  contact:        boolean;
}

export interface Certification {
  title:         string;
  issuer:        string;
  date:          string;
  credentialUrl: string;
  badgeUrl:      string;
  tags:          string[];
}

// Re-export with proper types applied
export const config = {
  ...rawConfig,
  colorPreset:  rawConfig.colorPreset  as ColorPreset,
  defaultTheme: rawConfig.defaultTheme as "system" | "light" | "dark",
  sections:     rawConfig.sections     as SectionVisibility,
  certifications: (rawConfig.certifications ?? []) as Certification[],

  // Only used when colorPreset is "custom".
  customColors: (rawConfig as unknown as { customColors?: PresetPalette })
    .customColors,
};
